version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: emby-mysql
    environment:
      MYSQL_ROOT_PASSWORD: emby_balance_root
      MYSQL_DATABASE: emby_balance
      MYSQL_USER: emby_user
      MYSQL_PASSWORD: emby_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - emby-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Emby Balance Java服务 + Nginx劫持
  emby-balance:
    build:
      context: .
      dockerfile: docker/emby-balance/Dockerfile
    container_name: emby-balance
    environment:
      JAVA_OPTS: "-Xmx1g -Xms512m"
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/emby_balance?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: emby_user
      SPRING_DATASOURCE_PASSWORD: emby_password
      EMBY_SERVER_HOST: emby-server
      EMBY_SERVER_PORT: 8096
      NGINX_DOWNLOAD_HOST: nginx-download
      NGINX_DOWNLOAD_PORT: 80
    volumes:
      - app_data:/app/data
      - app_logs:/var/log
    ports:
      - "80:80"      # Nginx代理端口
      - "8080:8080"  # Spring Boot端口
    networks:
      - emby-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx下载和统计模块
  nginx-download:
    build:
      context: .
      dockerfile: docker/nginx-download/Dockerfile
    container_name: nginx-download
    environment:
      EMBY_SERVER_HOST: emby-server
      EMBY_SERVER_PORT: 8096
      SPRING_BOOT_HOST: emby-balance
      SPRING_BOOT_PORT: 8080
      MEDIA_ROOT: /var/lib/emby/media
    volumes:
      - media_files:/var/lib/emby/media:ro  # 只读挂载媒体文件
      - download_logs:/var/log/nginx
    ports:
      - "8081:80"  # 下载服务端口
    networks:
      - emby-network
    depends_on:
      - emby-balance
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Emby服务器（可选，如果您已有Emby服务器可以移除此部分）
  emby-server:
    image: emby/embyserver:latest
    container_name: emby-server
    environment:
      UID: 1000
      GID: 1000
      GIDLIST: 1000
    volumes:
      - emby_config:/config
      - media_files:/mnt/media:ro
    ports:
      - "8096:8096"  # Emby Web端口
      - "8920:8920"  # Emby HTTPS端口
    networks:
      - emby-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mysql_data:
    driver: local
  app_data:
    driver: local
  app_logs:
    driver: local
  download_logs:
    driver: local
  emby_config:
    driver: local
  media_files:
    driver: local
    # 如果您有现有的媒体文件目录，可以使用以下配置：
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /path/to/your/media/files

networks:
  emby-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16